name: CI
on:
  - push
jobs:
  code_GitHub:
    runs-on: ubuntu-22.04
    steps:
      - name: Récuperer le code depuis Github 
        uses: actions/checkout@v4

      - name : Node_JS
        uses: actions/setup-node@v4
        with:
          node-version: 20.17

      - run : npm run build
      - run : npm ci